version: '3'
services:

  # database
  db:
    image: mysql:8.0 
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      default:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bot
      MYSQL_PASSWORD: password

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    networks:
      default:
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

  # caches
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      default:
    restart: always
    ports:
      - 6379:6379

  # python
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    networks:
      default:
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: "web.settings"
  
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "10.8.11.0/24"
      
volumes:
  db_data: